In [1]:
import pandas as pd
import pickle
import joblib

In [2]:
movies = pd.read_csv('TMDB_10K_Movie_Dataset.csv')

In [3]:
movies.head(10)

,id,title,genres,overview,release_date,popularity,vote_average,vote_count,cast,director,poster_path,original_language
0,19995,Avatar,"['Action', 'Adventure', 'Fantasy', 'ScienceFic...","['In', 'the', '22nd', 'century,', 'a', 'parapl...",10/12/2009,150.437577,7.2,11800,"['SamWorthington', 'ZoeSaldana', 'SigourneyWea...",['JamesCameron'],/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,en
1,285,Pirates of the Caribbean: At World's End,"['Adventure', 'Fantasy', 'Action']","['Captain', 'Barbossa,', 'long', 'believed', '...",19/05/2007,139.082615,6.9,4500,"['JohnnyDepp', 'OrlandoBloom', 'KeiraKnightley']",['GoreVerbinski'],/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg,en
2,206647,Spectre,"['Action', 'Adventure', 'Crime']","['A', 'cryptic', 'message', 'from', 'Bond’s', ...",26/10/2015,107.376788,6.3,4466,"['DanielCraig', 'ChristophWaltz', 'LéaSeydoux']",['SamMendes'],/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg,en
3,49026,The Dark Knight Rises,"['Action', 'Crime', 'Drama', 'Thriller']","['Following', 'the', 'death', 'of', 'District'...",16/07/2012,112.312950,7.6,9106,"['ChristianBale', 'MichaelCaine', 'GaryOldman']",['ChristopherNolan'],/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg,en
4,49529,John Carter,"['Action', 'Adventure', 'ScienceFiction']","['John', 'Carter', 'is', 'a', 'war-weary,', 'f...",07/03/2012,43.926995,6.1,2124,"['TaylorKitsch', 'LynnCollins', 'SamanthaMorton']",['AndrewStanton'],/lCxz1Yus07QCQQCb6I0Dr3Lmqpx.jpg,en
5,559,Spider-Man 3,"['Fantasy', 'Action', 'Adventure']","['The', 'seemingly', 'invincible', 'Spider-Man...",01/05/2007,115.699814,5.9,3576,"['TobeyMaguire', 'KirstenDunst', 'JamesFranco']",['SamRaimi'],/qFmwhVUoUSXjkKRmca5yGDEXBIj.jpg,en
6,38757,Tangled,"['Animation', 'Family']","['When', 'the', ""kingdom's"", 'most', 'wanted-a...",24/11/2010,48.681969,7.4,3330,"['ZacharyLevi', 'MandyMoore', 'DonnaMurphy']",['ByronHoward'],/ym7Kst6a4uodryxqbGOxmewF235.jpg,en
7,99861,Avengers: Age of Ultron,"['Action', 'Adventure', 'ScienceFiction']","['When', 'Tony', 'Stark', 'tries', 'to', 'jump...",22/04/2015,134.279229,7.3,6767,"['RobertDowneyJr.', 'ChrisHemsworth', 'MarkRuf...",['JossWhedon'],/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,en
8,767,Harry Potter and the Half-Blood Prince,"['Adventure', 'Fantasy', 'Family']","['As', 'Harry', 'begins', 'his', 'sixth', 'yea...",07/07/2009,98.885637,7.4,5293,"['DanielRadcliffe', 'RupertGrint', 'EmmaWatson']",['DavidYates'],/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg,en
9,209112,Batman v Superman: Dawn of Justice,"['Action', 'Adventure', 'Fantasy']","['Fearing', 'the', 'actions', 'of', 'a', 'god-...",23/03/2016,155.790452,5.7,7004,"['BenAffleck', 'HenryCavill', 'GalGadot']",['ZackSnyder'],/5UsK3grJvtQrtzEgqNlDljJW96w.jpg,en

In [4]:
movies.describe()

                 id   popularity  vote_average    vote_count
count  9.838000e+03  9838.000000   9838.000000   9838.000000
mean   1.712379e+05    26.656448      6.386834    938.833096
std    2.542203e+05    68.066094      1.056504   1797.815006
min    5.000000e+00     0.000000      0.000000      0.000000
25%    1.042525e+04    13.220000      5.893000    132.000000
50%    2.853950e+04    16.737367      6.500000    364.000000
75%    2.780740e+05    26.288488      7.071000    951.000000
max    1.175306e+06  2994.357000     10.000000  27713.000000

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9838 entries, 0 to 9837
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 9838 non-null   int64
 1   title              9838 non-null   object
 2   genres             9838 non-null   object
 3   overview           9838 non-null   object
 4   release_date       9837 non-null   object
 5   popularity         9838 non-null   float64
 6   vote_average       9838 non-null   float64
 7   vote_count         9838 non-null   int64
 8   cast               9838 non-null   object
 9   director           9778 non-null   object
 10  poster_path        9815 non-null   object
 11  original_language  9830 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 922.4+ KB

In [6]:
movies.isnull().sum()

id                    0
title                 0
genres                0
overview              0
release_date          1
popularity            0
vote_average          0
vote_count            0
cast                  0
director             60
poster_path          23
original_language     8
dtype: int64

FEATURE SELECTION PART

In [7]:
movies.columns

Index(['id', 'title', 'genres', 'overview', 'release_date', 'popularity',
       'vote_average', 'vote_count', 'cast', 'director', 'poster_path',
       'original_language'],
      dtype='object')

In [8]:
movies = movies[['id','title','genres','overview','release_date','cast', 'director', 'poster_path','original_language']]

In [9]:
movies

,id,title,genres,overview,release_date,cast,director,poster_path,original_language
0,19995,Avatar,"['Action', 'Adventure', 'Fantasy', 'ScienceFic...","['In', 'the', '22nd', 'century,', 'a', 'parapl...",10/12/2009,"['SamWorthington', 'ZoeSaldana', 'SigourneyWea...",['JamesCameron'],/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,en
1,285,Pirates of the Caribbean: At World's End,"['Adventure', 'Fantasy', 'Action']","['Captain', 'Barbossa,', 'long', 'believed', '...",19/05/2007,"['JohnnyDepp', 'OrlandoBloom', 'KeiraKnightley']",['GoreVerbinski'],/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg,en
2,206647,Spectre,"['Action', 'Adventure', 'Crime']","['A', 'cryptic', 'message', 'from', 'Bond’s', ...",26/10/2015,"['DanielCraig', 'ChristophWaltz', 'LéaSeydoux']",['SamMendes'],/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg,en
3,49026,The Dark Knight Rises,"['Action', 'Crime', 'Drama', 'Thriller']","['Following', 'the', 'death', 'of', 'District'...",16/07/2012,"['ChristianBale', 'MichaelCaine', 'GaryOldman']",['ChristopherNolan'],/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg,en
4,49529,John Carter,"['Action', 'Adventure', 'ScienceFiction']","['John', 'Carter', 'is', 'a', 'war-weary,', 'f...",07/03/2012,"['TaylorKitsch', 'LynnCollins', 'SamanthaMorton']",['AndrewStanton'],/lCxz1Yus07QCQQCb6I0Dr3Lmqpx.jpg,en
...,...,...,...,...,...,...,...,...,...
9833,8289,Gorky Park,"['Thriller', 'Crime', 'Drama']","['Police', 'Inspector', 'Renko', 'tries', 'to'...",15/12/1983,"['William Hurt', 'Lee Marvin', 'Brian Dennehy']",Michael Apted,/jRUUE2ehADlwMhb33s8UskYhTXS.jpg,en
9834,19673,Sexmission,"['ScienceFiction', 'Adventure', 'Comedy']","['Two', 'scientists', 'are', 'chosen', 'as', '...",13/05/1984,"['Olgierd Łukaszewicz', 'Jerzy Stuhr', 'Bożena...",Juliusz Machulski,/8zh3AuXBxGbgtebL5DpaDxJgMeW.jpg,pl
9835,24229,The Killers,"['Crime', 'Mystery']","['A', 'hit', 'man', 'and', 'his', 'partner', '...",07/07/1964,"['Lee Marvin', 'Angie Dickinson', 'John Cassav...",Don Siegel,/7IeXjRmUZ2pnSFMRh0ZXpu3Nkmn.jpg,en
9836,29380,Easter Parade,"['Romance', 'Music']","['On', 'the', 'day', 'before', 'Easter', 'in',...",08/07/1948,"['Judy Garland', 'Fred Astaire', 'Peter Lawford']",Charles Walters,/aLgvafQvb6D6at4khC0b7kn0h8f.jpg,en
9837,17038,Lake Placid 2,"['Horror', 'ScienceFiction']","['Man-eating', 'crocodiles', 'return', 'to', '...",28/04/2007,"['John Schneider', 'Sam McMurray', 'Sarah Lafl...",David Flores,/6ju8eLIai0hux6DSkIwRUozbX7K.jpg,en

In [10]:
movies['tags'] = movies['genres'] + movies['overview'] + movies['cast'] + movies['director'] + movies['original_language']

In [11]:
movies

,id,title,genres,overview,release_date,cast,director,poster_path,original_language,tags
0,19995,Avatar,"['Action', 'Adventure', 'Fantasy', 'ScienceFic...","['In', 'the', '22nd', 'century,', 'a', 'parapl...",10/12/2009,"['SamWorthington', 'ZoeSaldana', 'SigourneyWea...",['JamesCameron'],/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,en,"['Action', 'Adventure', 'Fantasy', 'ScienceFic..."
1,285,Pirates of the Caribbean: At World's End,"['Adventure', 'Fantasy', 'Action']","['Captain', 'Barbossa,', 'long', 'believed', '...",19/05/2007,"['JohnnyDepp', 'OrlandoBloom', 'KeiraKnightley']",['GoreVerbinski'],/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg,en,"['Adventure', 'Fantasy', 'Action']['Captain', ..."
2,206647,Spectre,"['Action', 'Adventure', 'Crime']","['A', 'cryptic', 'message', 'from', 'Bond’s', ...",26/10/2015,"['DanielCraig', 'ChristophWaltz', 'LéaSeydoux']",['SamMendes'],/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg,en,"['Action', 'Adventure', 'Crime']['A', 'cryptic..."
3,49026,The Dark Knight Rises,"['Action', 'Crime', 'Drama', 'Thriller']","['Following', 'the', 'death', 'of', 'District'...",16/07/2012,"['ChristianBale', 'MichaelCaine', 'GaryOldman']",['ChristopherNolan'],/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg,en,"['Action', 'Crime', 'Drama', 'Thriller']['Foll..."
4,49529,John Carter,"['Action', 'Adventure', 'ScienceFiction']","['John', 'Carter', 'is', 'a', 'war-weary,', 'f...",07/03/2012,"['TaylorKitsch', 'LynnCollins', 'SamanthaMorton']",['AndrewStanton'],/lCxz1Yus07QCQQCb6I0Dr3Lmqpx.jpg,en,"['Action', 'Adventure', 'ScienceFiction']['Joh..."
...,...,...,...,...,...,...,...,...,...,...
9833,8289,Gorky Park,"['Thriller', 'Crime', 'Drama']","['Police', 'Inspector', 'Renko', 'tries', 'to'...",15/12/1983,"['William Hurt', 'Lee Marvin', 'Brian Dennehy']",Michael Apted,/jRUUE2ehADlwMhb33s8UskYhTXS.jpg,en,"['Thriller', 'Crime', 'Drama']['Police', 'Insp..."
9834,19673,Sexmission,"['ScienceFiction', 'Adventure', 'Comedy']","['Two', 'scientists', 'are', 'chosen', 'as', '...",13/05/1984,"['Olgierd Łukaszewicz', 'Jerzy Stuhr', 'Bożena...",Juliusz Machulski,/8zh3AuXBxGbgtebL5DpaDxJgMeW.jpg,pl,"['ScienceFiction', 'Adventure', 'Comedy']['Two..."
9835,24229,The Killers,"['Crime', 'Mystery']","['A', 'hit', 'man', 'and', 'his', 'partner', '...",07/07/1964,"['Lee Marvin', 'Angie Dickinson', 'John Cassav...",Don Siegel,/7IeXjRmUZ2pnSFMRh0ZXpu3Nkmn.jpg,en,"['Crime', 'Mystery']['A', 'hit', 'man', 'and',..."
9836,29380,Easter Parade,"['Romance', 'Music']","['On', 'the', 'day', 'before', 'Easter', 'in',...",08/07/1948,"['Judy Garland', 'Fred Astaire', 'Peter Lawford']",Charles Walters,/aLgvafQvb6D6at4khC0b7kn0h8f.jpg,en,"['Romance', 'Music']['On', 'the', 'day', 'befo..."
9837,17038,Lake Placid 2,"['Horror', 'ScienceFiction']","['Man-eating', 'crocodiles', 'return', 'to', '...",28/04/2007,"['John Schneider', 'Sam McMurray', 'Sarah Lafl...",David Flores,/6ju8eLIai0hux6DSkIwRUozbX7K.jpg,en,"['Horror', 'ScienceFiction']['Man-eating', 'cr..."

In [12]:
new_data = movies.drop(columns=['genres','overview','cast','director','original_language'])

In [13]:
new_data

,id,title,release_date,poster_path,tags
0,19995,Avatar,10/12/2009,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,"['Action', 'Adventure', 'Fantasy', 'ScienceFic..."
1,285,Pirates of the Caribbean: At World's End,19/05/2007,/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg,"['Adventure', 'Fantasy', 'Action']['Captain', ..."
2,206647,Spectre,26/10/2015,/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg,"['Action', 'Adventure', 'Crime']['A', 'cryptic..."
3,49026,The Dark Knight Rises,16/07/2012,/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg,"['Action', 'Crime', 'Drama', 'Thriller']['Foll..."
4,49529,John Carter,07/03/2012,/lCxz1Yus07QCQQCb6I0Dr3Lmqpx.jpg,"['Action', 'Adventure', 'ScienceFiction']['Joh..."
...,...,...,...,...,...
9833,8289,Gorky Park,15/12/1983,/jRUUE2ehADlwMhb33s8UskYhTXS.jpg,"['Thriller', 'Crime', 'Drama']['Police', 'Insp..."
9834,19673,Sexmission,13/05/1984,/8zh3AuXBxGbgtebL5DpaDxJgMeW.jpg,"['ScienceFiction', 'Adventure', 'Comedy']['Two..."
9835,24229,The Killers,07/07/1964,/7IeXjRmUZ2pnSFMRh0ZXpu3Nkmn.jpg,"['Crime', 'Mystery']['A', 'hit', 'man', 'and',..."
9836,29380,Easter Parade,08/07/1948,/aLgvafQvb6D6at4khC0b7kn0h8f.jpg,"['Romance', 'Music']['On', 'the', 'day', 'befo..."
9837,17038,Lake Placid 2,28/04/2007,/6ju8eLIai0hux6DSkIwRUozbX7K.jpg,"['Horror', 'ScienceFiction']['Man-eating', 'cr..."

Feature Extraction

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tfidf = TfidfVectorizer(max_features=5000, stop_words='english', ngram_range=(1,2))

In [17]:
vectors = tfidf.fit_transform(new_data['tags'].values.astype('U'))

In [18]:
vectors.shape

(9838, 5000)

In [20]:
pickle.dump(
    new_data,
    open('movies_list.pkl', 'wb')
)

joblib.dump(
    vectors,
    'vectors.pkl',
    compress=3
)

joblib.dump(
    tfidf,
    'vectorizer.pkl',
    compress=3
)

['vectorizer.pkl']

In [22]:
pickle.load(open('movies_list.pkl','rb'))

,id,title,release_date,poster_path,tags
0,19995,Avatar,10/12/2009,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,"['Action', 'Adventure', 'Fantasy', 'ScienceFic..."
1,285,Pirates of the Caribbean: At World's End,19/05/2007,/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg,"['Adventure', 'Fantasy', 'Action']['Captain', ..."
2,206647,Spectre,26/10/2015,/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg,"['Action', 'Adventure', 'Crime']['A', 'cryptic..."
3,49026,The Dark Knight Rises,16/07/2012,/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg,"['Action', 'Crime', 'Drama', 'Thriller']['Foll..."
4,49529,John Carter,07/03/2012,/lCxz1Yus07QCQQCb6I0Dr3Lmqpx.jpg,"['Action', 'Adventure', 'ScienceFiction']['Joh..."
...,...,...,...,...,...
9833,8289,Gorky Park,15/12/1983,/jRUUE2ehADlwMhb33s8UskYhTXS.jpg,"['Thriller', 'Crime', 'Drama']['Police', 'Insp..."
9834,19673,Sexmission,13/05/1984,/8zh3AuXBxGbgtebL5DpaDxJgMeW.jpg,"['ScienceFiction', 'Adventure', 'Comedy']['Two..."
9835,24229,The Killers,07/07/1964,/7IeXjRmUZ2pnSFMRh0ZXpu3Nkmn.jpg,"['Crime', 'Mystery']['A', 'hit', 'man', 'and',..."
9836,29380,Easter Parade,08/07/1948,/aLgvafQvb6D6at4khC0b7kn0h8f.jpg,"['Romance', 'Music']['On', 'the', 'day', 'befo..."
9837,17038,Lake Placid 2,28/04/2007,/6ju8eLIai0hux6DSkIwRUozbX7K.jpg,"['Horror', 'ScienceFiction']['Man-eating', 'cr..."

Recommend Function

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [ ]:
def recommend(movie):

    # FIND MOVIE INDEX
    movie_index = new_data[new_data['title'] == movie].index[0]

    # GET VECTOR OF SELECTED MOVIE
    movie_vector = vectors[movie_index]

    # COMPUTE SIMILARITY DYNAMICALLY
    similarity = cosine_similarity(movie_vector, vectors).flatten()

    # GET TOP SIMILAR MOVIES
    distances = sorted(
        list(enumerate(similarity)),
        reverse=True,
        key=lambda x: x[1]
    )[1:11]

    # STORE RESULTS
    recommended_movies = []

    for i in distances:
        recommended_movies.append(new_data.iloc[i[0]].title)

    return recommended_movies

In [27]:
recommend("Interstellar")

['Space Pirate Captain Harlock',
 'Winnie Mandela',
 'Midnight Special',
 'Mud',
 'Solaris',
 'A Trip to the Moon',
 '20,000 Leagues Under the Sea',
 'The Green Inferno',
 'Dawn of the Crescent Moon',
 'Berserk: The Golden Age Arc II - The Battle for Doldrey']

In [26]:
recommend("3 Idiots")

['Mohabbatein',
 'Love, Rosie',
 'Van Wilder 2: The Rise of Taj',
 'Like Crazy',
 'Funny Ha Ha',
 'Loser',
 'Animal House',
 'Steppin: The Movie',
 'Paris, Texas',
 'Frat Party']